services:
    frontend:
      build: ./frontend
      container_name: frontend
      restart: always
      ports:
        - ${FRONTEND_PORT}:3000
      env_file:
        - .env
      volumes:
        - ./frontend:/app
        - /app/node_modules
    backend:
      build: ./backend
      container_name: backend
      restart: always
      ports:
        - ${BACKEND_PORT}:8000
      env_file:
        - .env
      volumes:
        - ./backend:/app
    db:
      image: postgres:17
      container_name: Portfolio
      restart: always
      env_file:
        - .env
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: