services:
    frontend:
      build: ./frontend
      container_name: frontend
      restart: always
      ports:
        - ${FRONTEND_PORT}:3000
      env_file:
        - .env
    backend:
      build: ./backend
      container_name: backend
      restart: always
      ports:
        - ${BACKEND_PORT}:8000
      env_file:
        - .env
        - frontend/.env.local
    db:
      image: postgres:17
      container_name: Portfolio
      restart: always
      env_file:
        - .env
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./frontend/out:/usr/share/nginx/html:ro
volumes:
  postgres_data: