services:
    backend:
      bild:
      
    db:
      image: postgres:17
      container_name: Timer
      restart: always
      env_file:
        - .env
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: