"""add column username

Revision ID: 9f15d32068a0
Revises: d419d9e72d55
Create Date: 2025-08-03 20:18:24.209196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f15d32068a0'
down_revision: Union[str, Sequence[str], None] = 'd419d9e72d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyhistory', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyhistory', 'username')
    # ### end Alembic commands ###
