"""add column user_id

Revision ID: 59db9c4cd195
Revises: 84e8b5db04b9
Create Date: 2025-08-09 10:46:51.639818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59db9c4cd195'
down_revision: Union[str, Sequence[str], None] = '84e8b5db04b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule', 'users', ['user_id'], ['id'])
    op.add_column('studyhistory', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'studyhistory', 'users', ['user_id'], ['id'])
    op.add_column('timer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timer', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timer', type_='foreignkey')
    op.drop_column('timer', 'user_id')
    op.drop_constraint(None, 'studyhistory', type_='foreignkey')
    op.drop_column('studyhistory', 'user_id')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'user_id')
    # ### end Alembic commands ###
