"""change StudyHistory

Revision ID: 9f84ae257673
Revises: 2e43e32afecf
Create Date: 2025-07-19 15:05:19.791266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f84ae257673'
down_revision: Union[str, Sequence[str], None] = '2e43e32afecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studyhistory', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_column('studyhistory', 'endTime')
    op.drop_column('studyhistory', 'startTime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyhistory', sa.Column('startTime', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('studyhistory', sa.Column('endTime', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('studyhistory', 'date',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
